trigger:
- sandbox

pool:
  vmImage: 'ubuntu-latest'

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: CreateACR
  displayName: Create Azure Container Registry
  jobs:
  - job: CreateACRJob
    displayName: Create ACR Job
    steps:
    - task: AzureCLI@2
      displayName: Create Azure Container Registry
      inputs:
        azureSubscription: $(subscriptionName)
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az acr create \
            --name $(registryName) \
            --resource-group $(resourceGroupName) \
            --location $(location) \
            --sku $(sku) \
            --admin-enabled false

- stage: BuildAndPushImage
  displayName: Build and Push Docker Image
  dependsOn: CreateACR
  jobs:
  - job: BuildAndPushImageJob
    displayName: Build and Push Image Job
    steps:
    - task: Docker@2
      displayName: Login to ACR
      inputs:
        command: login
        containerRegistry: $(ACRServiceConnection)
        azureSubscription: $(subscriptionName)

    - task: Docker@2
      displayName: Build and Push Docker Image
      inputs:
        command: buildAndPush
        repository: $(registryName).azurecr.io/$(imageName)
        containerRegistry: 'ACRServiceConnection'
        azureSubscription: $(subscriptionName)
        dockerfile: '**/WebApp.Dockerfile'
        tags: |
          $(tag)

